### ISSUE TITLE
DRS

### ISSUE THREAD

**Issue by yanet-02** [SistemasTecTlaxiaco/actividad-7-documento-de-especificacion-de-requerimientos-equipo-yce#4]
[DOCUMENTO DRS --.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-documento-de-especificacion-de-requerimientos-equipo-yce/files/13385627/DOCUMENTO.DRS.--.pdf)

**Comment by josealfredo79** [comment]
Calificacion???

**Comment by Alvaro2-0** [comment]
28/30

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
